version: "3"
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storyway
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring

  backend:
    image: storyway:v1
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - spring
    depends_on:
      - mysql
    volumes:
      - "C:\\Users\\harsh\\Downloads\\StoryWay\\StoryWay\\src\\main\\resources:/config"
    environment:
      SPRING_CONFIG_LOCATION: /config/application.properties

networks:
  spring:

volumes:
  mysql-data:
