# Service Configuration
service:
  name: storyway
  version: 1.0.0
  description: StoryWay - A malware detection service using machine learning and PE file analysis

# Deployment Configuration
deployment:
  environment: production # Set to 'development' or 'staging' as needed
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

# Authentication Configuration
auth:
  type: jwt
  secret: my-secret-key # Update with your actual secret key
  issuer: storyway-issuer
  audience: storyway-audience

# Environment Variables
env:
  - name: DATABASE_URL
    value: "jdbc:mysql://localhost:3306/storyway_db"
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: jwt_key
  - name: LOG_LEVEL
    value: "info"

# Logging Configuration
logging:
  level: info # or debug, warn, error based on the environment
  format: json # or text
  output: stdout

# Networking Configuration
network:
  port: 8080
  protocol: http # Change to https if using SSL
  cors:
    enabled: true
    allowedOrigins:
      - "*" # Update with specific origins in production
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

# Monitoring and Alerts
monitoring:
  enabled: true
  endpoint: "/actuator/metrics" # Adjust based on your Spring Boot actuator setup
  alerts:
    - type: threshold
      metric: cpu_usage
      threshold: 80
      action: scale_up

# Added Configuration from Suggestions
# Build Permissions
build:
  permissions:
    executableScripts:
      - mvnw

# CI/CD Configuration
cicd:
  steps:
    - name: Set Executable Permissions
      command: chmod +x mvnw
    - name: Build Application
      command: ./mvnw clean package -DskipTests

# Error Handling
errorHandling:
  retry: 3
  timeout: 30s
  logLevel: error

# Security Settings
security:
  https: false # Change to true if SSL is configured
  xssProtection: enabled
  contentSecurityPolicy: "default-src 'self'"

# Alerts Configuration
alerts:
  - type: email
    recipients:
      - admin@storyway.com
    onFailure: true
