spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/storyway
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true